services:
    napcat_front:
        environment:
            - ACCOUNT=
            - WSR_ENABLE=true
            - WS_URLS=["ws://nonebot:8080/onebot/v11/ws"]
            - NAPCAT_UID=
            - NAPCAT_GID=
        ports:
           - 6099:6099
        volumes:
           - ./front/QQ:/app/.config/QQ
           - ./front/napcat:/app/napcat/config
        restart: always
        hostname: napcat_front
        image: mlikiowa/napcat-docker:latest
    napcat_backend:
        environment:
            - ACCOUNT=
            - WSR_ENABLE=true
            - WS_URLS=["ws://nonebot:8080/onebot/v11/ws"]
            - NAPCAT_UID=
            - NAPCAT_GID=
        ports:
           - 6100:6099
        volumes:
           - ./backend/QQ:/app/.config/QQ
           - ./backend/napcat:/app/napcat/config
        restart: always
        hostname: napcat_backend
        image: mlikiowa/napcat-docker:latest
    nonebot:
        env_file:
            - ./.env.prod
        environment:
            HOST: 0.0.0.0
            PORT: 8080
        image: helpdesk-chatbot-nonebot
        volumes:
          - ./data:/app/data
          - .env.prod:/app/.env.prod
        hostname: nonebot
        restart: always