"""first revision

迁移 ID: 43e51beb9380
父迁移: 
创建时间: 2024-10-18 15:18:35.552332

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '43e51beb9380'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('csts',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csts_ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('engineer_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATING', 'PENDING', 'PROCESSING', 'ALARMING', 'CLOSED', 'SCHEDULED', name='status'), nullable=False),
    sa.Column('begin_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('creating_expired_at', sa.DateTime(), nullable=False),
    sa.Column('alarming_expired_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_csts_ticket')),
    info={'bind_key': 'csts'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csts_ticket')
    # ### end Alembic commands ###
