"""add schedule time string

迁移 ID: 6cf56855cbc2
父迁移: 43e51beb9380
创建时间: 2024-10-19 14:38:02.654386

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6cf56855cbc2'
down_revision: str | Sequence[str] | None = '43e51beb9380'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csts_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csts_ticket', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###
